config/routes.rb
Rails.application.routes.draw do
  resource :user, only: [:edit, :update]
  resources :pets
  resources :care_providers

  root 'homepage#index'

  patch 'user/edit' => 'care_provider#index'

  get    '/auth/:provider'          => 'omniauth#auth',    as: :auth
  get    '/auth/:provider/callback' => 'session#create'
  get    '/auth/failure'            => 'session#failure'


  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/care_provider.rb
class CareProvider < ApplicationRecord
  has_many :specializations
  has_many :pet_types, through: :specializations

  validates :name, presence: true
  validates :address, presence: true
  validates :website, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  belongs_to :pet_type
  has_many :care_providers, through: :pet_type

  def pet_type_name
    pet_type ? pet_type.type_of_pet : "Pet"
  end
end

app/models/pet_type.rb
class PetType < ApplicationRecord
  has_many :specializations
  has_many :care_providers, through: :specializations
end

app/models/specialization.rb
class Specialization < ApplicationRecord
  belongs_to :care_provider
  belongs_to :pet_type
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  has_many :care_providers, through: :pets
  # Factory method to create a user from some omniauth data
  # Omniauth will use this to build a *NEW* user for us
  def self.from_omniauth(authentication_data)
    user = User.where(provider: authentication_data['provider'],
                      uid: authentication_data['uid']).first_or_create

    Rails.logger.debug "The user is #{user.inspect}"

    user.name         = authentication_data.info.name
    user.nickname     = authentication_data.info.nickname
    user.access_token = authentication_data.info.access_token

    user.save!

    Rails.logger.debug "After saving, the user is #{user.inspect}"

    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    # Assign the current user
  def current_user=(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  helper_method :current_user

  # Returns a boolean representing if the user is logged in
  def logged_in?
    !!current_user
  end
  helper_method :logged_in?

  # Method to use in filter to ensure the user is logged in
  def authenticate!
    unless logged_in?
      redirect_to login_path
    end
  end
  def remote_ip
    if request.remote_ip == '127.0.0.1'
      # Hard coded remote address
      '123.45.67.89'
    else
      request.remote_ip
    end
  end

end

app/controllers/care_providers_controller.rb
class CareProvidersController < ApplicationController
  before_action :set_care_provider, only: [:show, :edit, :update, :destroy]

  # GET /care_providers
  # GET /care_providers.json
  def index
    @ip = request.remote_ip
    # @ip = "108.190.18.85"

    geocoded = Geocoder.search(@ip).last
    if geocoded
      @lat = geocoded.latitude
      @lng = geocoded.longitude
    else
      @lat = 27.7723
      @lng = -82.6341
    end
    @care_providers = current_user.care_providers.near([@lat, @lng], 15, {order: "distance"}).distinct
  end

  # GET /care_providers/1
  # GET /care_providers/1.json
  def show
  end

  # GET /care_providers/new
  def new
    @care_provider = CareProvider.new
  end

  # GET /care_providers/1/edit
  def edit
  end

  # POST /care_providers
  # POST /care_providers.json
  def create
    @care_provider = CareProvider.new(care_provider_params)

    respond_to do |format|
      if @care_provider.save
        format.html { redirect_to @care_provider, notice: 'Care provider was successfully created.' }
        format.json { render :show, status: :created, location: @care_provider }
      else
        format.html { render :new }
        format.json { render json: @care_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /care_providers/1
  # PATCH/PUT /care_providers/1.json
  def update
    respond_to do |format|
      if @care_provider.update(care_provider_params)
        format.html { redirect_to @care_provider, notice: 'Care provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @care_provider }
      else
        format.html { render :edit }
        format.json { render json: @care_provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /care_providers/1
  # DELETE /care_providers/1.json
  def destroy
    @care_provider.destroy
    respond_to do |format|
      format.html { redirect_to care_providers_url, notice: 'Care provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_care_provider
      @care_provider = CareProvider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def care_provider_params
      params.fetch(:care_provider, {})
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    if logged_in?
      redirect_to care_providers_path
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def create
    # Create a new pet from the params (name and pet_type_id)
    @pet = current_user.pets.create(pets_params)

    # Create a view called   views/pets/create.js.erb with some jquery magic
  end

  def destroy
    @pet = Pet.find(params[:id])

    @pet.destroy
  end

private
  def pets_params
    params.require(:pet).permit(:name, :pet_type_id)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  # logging in
  def new
  end

  # handle the post from the login page
  def create
    self.current_user = User.from_omniauth(request.env['omniauth.auth'])

    if current_user
      if current_user.pets.empty?
        redirect_to edit_user_path(current_user.id)
      else
        redirect_to care_providers_path
      end
    else
      redirect_to login_path
    end
  end

  # logout
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  # Show the failure page
  def failure
    # TODO, create failure.html.erb
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = current_user
    @pets = @user.pets
    @pet = Pet.new
    # redirect_to care_providers_path
  end

  def update
    @user = current_user

    if @user.update(user_params)
      redirect_to care_providers_path
    else
      render :edit
    end
  end

protected
  def user_params
    params.require(:user).permit(:name, :phone, :address, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def phone_number_link(text)
    link_to text, "tel:+1-#{text.scan(/[0-9]+/).join('-')}"
  end

  def navbar_footer_class
    logged_in? ? "navbar-bottom" : "navbar-fixed-bottom"
  end

  def body_class
    logged_in? ? "logged-in" : "logged-out"
  end
end

app/helpers/care_providers_helper.rb
module CareProvidersHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/care_providers/_form.html.erb
<%= form_for(care_provider) do |f| %>
  <% if care_provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(care_provider.errors.count, "error") %> prohibited this care_provider from being saved:</h2>

      <ul>
      <% care_provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/care_providers/delete.erb
    // googlemaps
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -34.397, lng: 150.644},
          zoom: 8
        });
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCubB-gRRS1uhP-O0reWXQ_npCHQ1p-m2Q&callback=initMap"
    async defer></script>

app/views/care_providers/edit.html.erb
<h1>Editing Care Provider</h1>

<%= render 'form', care_provider: @care_provider %>

<%= link_to 'Show', @care_provider %> |
<%= link_to 'Back', care_providers_path %>

app/views/care_providers/index.html.erb
<script>
$(document).ready(function() {
  var lat = <%= @lat %>;
  var lng = <%= @lng %>;

  var map = L.map('map').setView([lat, lng], 12);
  map.scrollWheelZoom.disable();
  // map.once('focus', function() { map.scrollWheelZoom.enable(); });


  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
    maxZoom: 18,
    touchZoom: false,
    id: 'mapbox.emerald',
    accessToken: 'pk.eyJ1IjoiYWZyb25jemFrIiwiYSI6ImNpdHQzM2d2ejA0eTIydG9icmtldm12Y3kifQ.jcj9k_1lKepTanCSvOVDEw'
  }).addTo(map);

  // Home marker
  var homeIcon = L.icon({
    iconUrl: '<%= image_path("rightmeow_catface200.svg") %>',
    iconRetinaUrl: '<%= image_path("rightmeow_catface200.svg") %>',
    iconSize: [38, 38]
  });
  L.marker([lat, lng], {icon: homeIcon}).addTo(map);

  var myIcon = L.icon({
    iconUrl: '<%= image_path("marker2.svg") %>',
    iconRetinaUrl: '<%= image_path("marker2.svg") %>',
    iconSize: [38, 38]
  });


  <% current_user.care_providers.distinct.each do |provider| %>
    var marker = L.marker([<%= provider.latitude %>, <%= provider.longitude %>], {icon: myIcon}).addTo(map);
    marker.bindPopup('<%= provider.name %><br/><%= link_to provider.website, provider.website.html_safe %><br/><%= provider.address %><br/><%= phone_number_link(provider.phone) %>');
  <% end %>
})
</script>



<div class="row app-bottom">
  <div class="col-lg-6">
    <div id="map"></div>
  </div>
  <div class="col-lg-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">Nearby Providers</h3>
      </div>
      <div class="panel-body">
        <ul class="list-group care-providers-list-group">
        <% @care_providers.each do |provider| %>
          <li class="list-group-item" data-toggle="modal" data-target="#provider-<%= provider.id%>">
            <span class="list-group-provider-name"><%= provider.name %></span>
            <span class="badge"><%= number_with_precision(provider.distance, precision: 2) %> mi </span>
          </li>
        <% end %>
        </ul>

        <% @care_providers.each do |provider| %>
          <div class="modal" id="provider-<%= provider.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                  <h4 class="modal-title" id="myModalLabel"><%= provider.name %></h4>
                </div>
                <div class="modal-body">
                  <ul class="list-group care-providers-detail">
                    <li class="list-group-item">
                      Website:
                      <span class="pull-right">
                        <%= link_to provider.name, provider.website.html_safe %>
                      </span>
                    </li>
                    <li class="list-group-item">
                      Phone:
                      <span class="pull-right">
                        <%= phone_number_link(provider.phone) %>
                      </span>
                    </li>
                    <li class="list-group-item">
                      Address:
                      <span class="pull-right">
                        <%= provider.address%>
                      </span>
                    </li>
                    <li class="list-group-item">
                      Specializations:
                      <span class="pull-right">
                        <% provider.pet_types.uniq.each do |type| %>
                          <%= image_tag("animals/svg/#{type.type_of_pet.tableize.singularize}.svg", title: type.type_of_pet, size: 20) %>
                        <% end %>
                      </span>
                    </li>
                  </ul>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
</div>

<!-- Modal -->
<div class="modal" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/0.7.3/leaflet.js"></script>

app/views/care_providers/new.html.erb
<h1>New Care Provider</h1>

<%= render 'form', care_provider: @care_provider %>

<%= link_to 'Back', care_providers_path %>

app/views/care_providers/provider_show.js.erb
$('.modal-toggle').on('click', function(e) {
  e.preventDefault();
  $('.modal').toggleClass('is-visible');
});

app/views/care_providers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_care_provider_path(@care_provider) %> |
<%= link_to 'Back', care_providers_path %>

app/views/homepage/index.html.erb
<div class="row">
  <div class="col-md-6 sign-up-container-left text-center">
    <%= image_tag("rightmeow_hospital200.svg", height: "250", class: "hospital") %>
  </div>
  <div class="col-md-6 sign-up-container-right flex-container">
    <div class="">
      <h3>
        Sign Up for an account using facebook to find care for your animal Right Meow!
      </h3>
      <div class="login_buttons text-center">
        <%= link_to auth_path(provider: 'facebook'), :class => "btn btn-block' btn-social btn-facebook" do %>
           <span class="fa fa-facebook"></span>
           Sign in with Facebook
         <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Right Meow!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Merienda+One" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body class="<%= body_class %>">
    <div class="col-lg-10 col-lg-offset-1 text-center">
      <%= image_tag("rightmeow_catface200.svg", size: '150', class: "top-icon")%>
      <h1 class="headline">Right Meow!</h1>
    </div>

    <div class="container-fluid wrapper">
        <div class="col-md-12 main">
          <% if logged_in? %>
            <div class="page-header logged-in">
              <h4>
                Hello
                <%= link_to "#{current_user.name}", edit_user_path %>
                <span class="pull-right"><%= link_to "Sign out", logout_path%></span>
              </h4>
            </div>
          <%end%>
          <%= yield %>
        </div>
      </div>
    </div>
    <div class="row footer-row">
      <div class="footer-align text-center col-sm-6 col-sm-offset-3">
        <p>
          Carefully crafted by <a href="http://adamfronczak.com">Adam Fronczak</a> at
          <%= link_to image_tag("TIY-Logo-500px-white.png", size: '40'), "https://www.theironyard.com/"%>
        </p>
      </div>
    </div>
    <div class="cloud-wrapper">
      <div class="cloud" data-type="white_4" style="top: 238px;" data-speed="1"></div>
      <div class="cloud" data-type="white_2" style="top: 252px;" data-speed="2"></div>
      <div class="cloud" data-type="white_1" style="top: 481px;" data-speed="3"></div>
      <div class="cloud" data-type="white_1" style="top: 285px;" data-speed="4"></div>
      <div class="cloud" data-type="white_5" style="top: 391px;" data-speed="5"></div>
      <div class="cloud" data-type="white_4" style="top: 410px;" data-speed="6"></div>
      <div class="cloud" data-type="white_6" style="top: 494px;" data-speed="7"></div>
      <div class="cloud" data-type="white_6" style="top: 197px;" data-speed="8"></div>
      <div class="cloud" data-type="white_1" style="top: 254px;" data-speed="9"></div>
      <div class="cloud" data-type="white_2" style="top: 108px;" data-speed="10"></div>
      <div class="cloud" data-type="white_5" style="top: 133px;" data-speed="11"></div>
      <div class="cloud" data-type="white_5" style="top: 126px;" data-speed="12"></div>
    </div>
  </body>
</html>

app/views/pets/_pet.html.erb
<li class="list-group-item col-lg-8" id="pet-<%= pet.id %>">
  <%= link_to '<i class="fa fa-times-circle" aria-hidden="true"></i>'.html_safe, pet_path(pet), :method => :delete, :remote => true, :data => { :confirm => 'Are you sure?'} %>

  <%= pet.name %></a>
  <span class="pull-right">
    <%= image_tag("animals/svg/#{pet.pet_type_name.tableize.singularize}.svg", title: pet.pet_type_name, size: 20) %>
    <%= pet.pet_type_name %>
  </span>
</li>

app/views/pets/create.js.erb
$('.user-pets').append("<%= j(render @pet) %>")

app/views/pets/destroy.js.erb
$('#pet-<%= @pet.id %>').remove()

app/views/users/edit.html.erb
<hr>
  <%= form_for @user, {:html => {:class => "forms-margin user_edit"}} do |f| %>
    <div class="form-group row">
      <%= f.label :name, class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :phone, class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :phone, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :address, class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :address, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :nickname, class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
        <%= f.text_field :nickname, class: "form-control" %>
      </div>
    </div>
  <%end%>

  <div class="form-group row forms-margin edit-pets">
    <div class="col-md-2">
      <label class="col-form-label">Pets</label>
    </div>
    <div class="col-md-10">
      <div class="pet-container row well">
        <div class="pet-form col-lg-9 col-md-9">
          <ul class="list-group user-pets">
            <%= render @pets %>
          </ul>
          <%= form_for @pet, { remote: true, html: { class: "form-inline form" } } do |f| %>
            <div class="form-group">
              <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
            </div>
            <div class="form-group">
                <%= f.collection_select(:pet_type_id, PetType.all, :id, :type_of_pet, {prompt: "Choose a type of pet"}, {class: "form-control"}) %>
            </div>
            <div class="form-group">
                <%= f.submit 'Add', class: 'btn btn-default pull-right' %>
            </div>
          <% end %>
        </div>
        <div class="right-meow-container col-lg-3 col-md-3 side-icons">
          <%= image_tag "rightmeow_fullcat200.svg"%>
        </div>
      </div>
    </div>
  </div>

  <div class="row user-edit-buttons">
    <div class="col-md-2 col-form-label"></div>
    <div class="col-md-10">
      <%= submit_tag 'Save', class: 'btn btn-primary user-form-submit' %>
      <%= link_to "Show Providers", root_path, class: "btn btn-info user-form-submit" %>
    </div>
  </div>